apiVersion: v1
kind: Service
metadata:
  name: your-service-name
spec:
  selector:
    app: your-app-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000
  type: LoadBalancer  # Use NodePort or ClusterIP as needed
